//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.06 at 12:29:03 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.drishticon.kukuscorner.ecommerce.carrier.model.jaxb.ups;
